packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@solidjs/router": ^0.16.2
  "@tailwindcss/vite": ^4.3.3
  solid-js: ^1.9.14
  tailwind-merge: ^3.6.0
  tailwind-variants: ^3.2.2
  tailwindcss: ^4.3.3

allowBuilds:
  esbuild: true
  sharp: true
  spawn-sync: true
